# Generated by Django 5.0.9 on 2026-06-16 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkr', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('prc', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], max_length=10)),
                ('act', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('qty', models.IntegerField()),
                ('lmt_prc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('st', models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('ast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ords', to='exchange.asset')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wlt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('ast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptf', to='exchange.asset')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usr', 'ast')},
            },
        ),
    ]
