# Generated by Django 5.0.9 on 2026-06-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol', models.IntegerField()),
                ('rec', models.CharField(max_length=10)),
                ('dt', models.DateTimeField(auto_now=True)),
                ('ast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sig', to='exchange.asset')),
            ],
        ),
    ]
